ad = input('Digite algo: ')
print('só tem espaços?', ad.isspace())
print('É alfanumerico?', ad.isalnum())
print('O tipo do que você digitou é:', type(ad))
print('O que você digitou é um número:', ad.isnumeric())
print('O que você digitou é uma letra:', ad.isalpha())
print('Está em maiusculas?', ad.isupper())
print('Está em minusculas?', ad.islower())
print('Está capitalizada?', ad.istitle())
print('O que você digitou é "printavel":', ad.isprintable())
